targets:
  $default:
    builders:
      drift_dev:
        options:
          write_from_json_string_constructor: true
      build_web_compilers:entrypoint:
        generate_for:
          - web/**.dart
        options:
          compiler: dart2js
        dev_options:
          dart2js_args:
            - --no-minify
        release_options:
          dart2js_args:
            - -O4
          # Other drift options can go here 